server:
  port: 8080

spring:
  application:
    name: sandbox
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          zkNodes: ${ZOOKEEPER_NODES:localhost:2181}
      bindings:
        firstTopic:
          destination: first_topic
        secondTopic:
          destination: second_topic

management:
  security:
    enabled: false

logging:
  pattern:
    console: "%date{ISO8601} [%thread] %level %logger - %msg%n"
  level:
    ROOT: INFO
    com.broadridge: DEBUG